force-app/main/default/objects/Class__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/College__c/fields/NAAC_Grade__c.field-meta.xml
<CustomField>
    <fullName>NAAC_Grade__c</fullName>
    <label>NAAC Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A++</fullName>
            </value>
            <value>
                <fullName>A+</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B++</fullName>
            </value>
            <value>
                <fullName>B+</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.College__c</field>
            <operation>equals</operation>
            <valueField>Class__c.College__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GetStudentDetails.cls
public class GetStudentDetails {
    public List<Student__c> getStudent(String collegeName, String studentName){
        List<Student__c> studentRecords = [SELECT Name, College__r.Name, Class__r.Name FROM Student__c WHERE College__r.Name=:collegeName AND Name=:StudentName];
        return studentRecords;
    }
    public List<Student__c> getCollege(String studentName){
        List<Student__c> collegeRecords = [SELECT Name,College__r.Name, College__r.CGPA__C, College__r.NAAC_Grade__c,College__r.Address__c FROM Student__c WHERE Name = :studentName];
        Return collegeRecords;
    }
}
/* GetStudentDetails t = new GetStudentDetails();
List<Student__c> tempStudentList = t.getStudent('CPA College', 'Muthu');
if(tempStudentList!= null && tempStudentList.size()>0){
    for(Student__c studentRec:tempStudentList){
        System.debug(studentRec.Name);
        System.debug(studentRec.Class__r.Name);
        System.debug(studentRec.College__r.Name);
    }
}else{
    System.debug('The Student Record is Invalid');
} */

/* GetStudentDetails t = new GetStudentDetails();
String name = 'A';
List<Student__c> tempStudentList = t.getCollege(name);
Set<College__c> tempSet = new Set<College__c>();
if(tempStudentList != null){
    for(Student__c stList : tempStudentList){
        College__c clg = new College__c();
        clg.Name = stList.College__r.Name;
        clg.CGPA__C = stList.College__r.CGPA__C;
        clg.NAAC_Grade__c = stList.College__r.NAAC_Grade__c;
        clg.Address__c = stList.College__r.Address__c;
        tempSet.add(clg);
    }
    for(College__c tempStu : tempSet){
        System.debug(tempStu.Name);
        System.debug(tempStu.CGPA__C);
        System.debug(tempStu.NAAC_Grade__c);
        System.debug(tempStu.Address__c);
    }
}else{
    System.debug('The Record is Invalid');
} */