force-app/main/default/objects/Class__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.College__c</field>
            <operation>equals</operation>
            <valueField>Class__c.College__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/college3.cls
public class college3 {
    public List<Student__c> studentList;

    public void getStudents(String collegeName1, String collegeName2, String departmentName, String studentName){
        studentList = [SELECT Name, Class__r.Name, College__r.Name FROM Student__c WHERE (College__r.Name = :collegeName1 OR College__r.Name = :collegeName2) AND (Class__r.Name = :departmentName AND Name = :studentName)];
    }
}

/* college3 t = new college3();

t.getStudents('CPA College', 'Kammavar College', 'CS-1', 'Muthu');

if(t.studentList.size() > 0){
    System.debug(' The Student Name is Exist ');
}else{
    System.debug(' The Student Name is Not Exist ');
} */