force-app/main/default/objects/Class__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.College__c</field>
            <operation>equals</operation>
            <valueField>Class__c.College__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Ms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/TotalMark__c.field-meta.xml
<CustomField>
    <fullName>TotalMark__c</fullName>
    <formula>Mark_1__c  +  Mark_2__c  + Mark_3__c  +Mark_4__c  + Mark_5__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TotalMark</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestMethod1.cls
public class TestMethod1 {
    /* public static void TestClassMehod(){
List <Student__c> tempList = [SELECT Name, Gender__c, Class__r.Name, Salutation__c FROM Student__c ORDER BY Gender__c, Name ASC];

Map<String, List<String>> tempMap = new Map<String, List<String>>();

For(Student__c tempList1 : tempList){
If(tempMap.ContainsKey(tempList1.Class__r.Name)){
List<String> lt1 = tempMap.get(tempList1.Class__r.Name);
lt1.add(tempList1.Name);
tempMap.put(tempList1.Class__r.Name, lt1);
}Else{
List<String> lt1 = new List<String>();
lt1.add(tempList1.Name);
tempMap.put(tempList1.Class__r.Name, lt1);
}
}System.debug(tempMap);
}*/
    Public static void tempmethod1(){
        List<Student__c> stuList = [SELECT Name, Class__r.Name, College__r.Name, TotalMark__c FROM Student__c];
        
        Map <String, List<String>> tempMap = new Map <String, List<String>>();
        
        Map<String, List<List<String>>> myMap = new Map<String, List<List<String>>>();
        
        
        For(Student__c stuList1 : stuList){ 
            If(tempMap.ContainsKey(stuList1.Class__r.Name)){
                List <String> templist = tempMap.get(stuList1.class__r.Name);
                templist.add(stuList1.Name);
                tempMap.put(stuList1.Class__r.Name, templist);
                
            }Else{
                /*List <String> templist = new List <String>();*/
                List<String> templist = null;
                templist.add(stuList1.Name);
                tempMap.put(stuList1.Class__r.Name, templist);                   
            }
            
            If(myMap.ContainsKey(stuList1.College__r.Name)){
                List<string> myList2 = tempMap.get(stuList1.Class__r.Name);
                List<List<String>> myList3 = new List<List<String>>();
                myList3.add(myList2);                
                myMap.put(stuList1.College__r.Name, myList3);
                
            }Else{
                List<String> myList2 = new List<String>();
                List<List<String>> myList3 = new List<List<String>>();
                myList3.add(myList2);
                myMap.put(stuList1.College__r.Name, myList3);
            }
            
        }System.debug(myMap);
    }
    public static void method11(){
        List<Integer> mark1 = new List<Integer>{70, 56, 34, 56, 40};
            List<Integer> mark2 = new List<Integer>{60, 26, 34, 56, 70};
                List<Integer> mark3 = new List<Integer>{70, 56, 74, 56, 40};
                    List<Integer> mark4 = new List<Integer>{20, 26, 34, 56, 10};
                        List<Integer> mark5 = new List<Integer>{30, 56, 34, 26, 20};
                            
                            List<List<Integer>> marks = new List<List<Integer>>();
        marks.add(mark1);
        marks.add(mark2);
        marks.add(mark3);
        marks.add(mark4);
        marks.add(mark5);
        marks.sort();
        System.debug('==================> ' + marks);
    }
}