force-app/main/default/objects/Class__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.College__c</field>
            <operation>equals</operation>
            <valueField>Class__c.College__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Roll_Number__c.field-meta.xml
<CustomField>
    <fullName>Roll_Number__c</fullName>
    <label>Roll Number</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateStudentRollNumber.cls
public class UpdateStudentRollNumber {
    public void updateRollNo(){
        List<Student__c> studentDetails = [SELECT Name, Roll_Number__c, College__c, Class__c FROM Student__c WHERE College__r.Name = 'Government College of Engineering(GCE)'];
        College__c clg = [SELECT Name FROM College__c WHERE Name = 'Government College of Engineering(GCE)'];
        for(Integer i=20001; i<20001+studentDetails.size(); i++){            
            for(Student__c stRec : studentDetails){
                Student__c stu = new Student__c();
                stu.College__c = clg.Id;
                stu.Name = stRec.Name;                
                stu.Roll_Number__c = String.valueOf(i); 
                update stu;
            }
            
        }
    }
}