force-app/main/default/objects/Class__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Departments__c.field-meta.xml
<CustomField>
    <fullName>Departments__c</fullName>
    <label>Departments</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B.sc(CS)</fullName>
            </value>
            <value>
                <fullName>B.sc(IT)</fullName>
            </value>
            <value>
                <fullName>BCA</fullName>
            </value>
            <value>
                <fullName>B.sc(Maths)</fullName>
            </value>
            <value>
                <fullName>B.sc(Chemistry)</fullName>
            </value>
            <value>
                <fullName>B.sc(Physics)</fullName>
            </value>
            <value>
                <fullName>B.com(CA)</fullName>
            </value>
            <value>
                <fullName>BBA</fullName>
            </value>
            <value>
                <fullName>EEE</fullName>
            </value>
            <value>
                <fullName>CSE</fullName>
            </value>
            <value>
                <fullName>Civil</fullName>
            </value>
            <value>
                <fullName>Mech</fullName>
            </value>
            <value>
                <fullName>MBBS</fullName>
            </value>
            <value>
                <fullName>BDS</fullName>
            </value>
            <value>
                <fullName>BUMS</fullName>
            </value>
            <value>
                <fullName>BAMS</fullName>
            </value>
            <value>
                <fullName>B.Pharm</fullName>
                <isActive>false</isActive>
                <label>B.Pharm</label>
            </value>
            <value>
                <fullName>M.Pharm</fullName>
                <isActive>false</isActive>
                <label>M.Pharm</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1st year</fullName>
            </value>
            <value>
                <fullName>2nd year</fullName>
            </value>
            <value>
                <fullName>3rd year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>( TODAY() - D_O_B__c )/365</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.College__c</field>
            <operation>equals</operation>
            <valueField>Class__c.College__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/D_O_B__c.field-meta.xml
<CustomField>
    <fullName>D_O_B__c</fullName>
    <label>D.O.B</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Roll_Number__c.field-meta.xml
<CustomField>
    <fullName>Roll_Number__c</fullName>
    <label>Roll Number</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/College2.cls
public class College2{
    
    public String nameOfTheCollege;
    public List<Class__c> departmentName(){
        List<Class__c> departmentDetails = [SELECT Name, Departments__c, Year__c, College__r.Name  FROM Class__c WHERE College__r.Name = :nameOfTheCollege ORDER BY Name ASC];
        return departmentDetails;        
    }
    public List<Student__c> studentName(){
        List<Student__c> studentDetails = [SELECT Name, Address__c, Age__c, Class__r.Name, College__r.Name, Contact_Number__c, D_O_B__c, E_Mail__c, Gender__c, Roll_Number__c FROM Student__c WHERE College__r.Name = :nameOfTheCollege ORDER BY Name ASC];       
        return studentDetails;
    }
}

/* College2 t = new College2();
t.nameOfTheCollege = 'CPA College';

List<Class__c> stList = t.departmentName();
for(Class__c dept : stList){
    System.debug(dept.Name);
}

List<Student__c> deptList = t.studentName();
for(Student__c stud : deptList){
    System.debug(stud.Name);
} */

/*College t = new College();
t.nameOfTheCollege = 'CPA College';

College__c test1 = new College__c();
test1 = t.collegeInfo();
if(test1 != null){
    System.debug(test1);
}


for(class__c departmentList : t.getDepartmentList()){
System.debug(departmentList.Name);
}

for(Student__c studentList : t.getStudentList()){
System.debug(studentList.Name);
}*/