force-app/main/default/objects/Class__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.College__c</field>
            <operation>equals</operation>
            <valueField>Class__c.College__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GetStudentInformation.cls
@RestResource(urlmapping='/studentinfo/*')
global class GetStudentInformation
{
    global class studentInfo
    {
        public String studentName{get;set;}
        public String phone{get;set;}
        public String address{get;set;}
        public String departmentName{get;set;}
        public String collegeName{get;set;}
    }

    @httpGet
    global static studentInfo getStudent()
    {
        studentInfo student = new studentInfo();
        RestRequest request = RestContext.request;
        System.debug('request.requestURI ' + request.requestURI);
        String studentId = request.requestURI.substring(request.requestURI.lastIndexOf('/') + 1);
        System.debug('studentId ' + studentId);

        if(String.isNotBlank(studentId))
        {
            Student__c studentRec = [SELECT Id, Name, Contact_Number__c, Address__c, Class__r.Name, College__r.Name FROM Student__c WHERE Id =: studentId LIMIT 1];
            student.studentName = studentRec.Name;
            student.phone = studentRec.Contact_Number__c;
            student.address = studentRec.Address__c;
            student.departmentName = studentRec.Class__r.Name;
            student.collegeName = studentRec.College__r.Name;
        }

        return student;
    }
}