force-app/main/default/objects/Class__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.College__c</field>
            <operation>equals</operation>
            <valueField>Class__c.College__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/StudentAdmissionHome.cls
public with sharing class StudentAdmissionHome{
    public List<SelectOption> collegeList {get;set;}
    public String selectedCollegeName {get;set;}
    public List<SelectOption> departmentList {get;set;}
    public String selectedDepartmentName {get;set;}
    public Boolean showDepartments {get;set;}
    public Student__c student {get;set;}
    public Contact con {get;set;}

    public StudentAdmissionHome()
    {
        collegeList = new List<SelectOption>();
        selectedCollegeName = '';
        departmentList = new List<SelectOption>();
        selectedDepartmentName = '';
        showDepartments = false;
        student = new Student__c();
        con = new Contact();
        getCollegeList();
    }

    public void getCollegeList()
    {
        List<College__c> collegeTempList = [SELECT Name, Id FROM College__c ORDER BY Name ASC];
        if(collegeTempList != null && collegeTempList.size() > 0)
        {
            for(College__c clg : collegeTempList)
            {
                List<SelectOption> options = new List<SelectOption>();
                if(collegeList.isEmpty()){
                    collegeList.add(new SelectOption('', '--None--'));
                }
                if (clg != null && clg.Name != null){
                    collegeList.add(new SelectOption(clg.Name, clg.Name));
                }
            }
        }
    }

    public void getDepartmentList()
    {
        departmentList = new List<SelectOption>();
        showDepartments = false;
        if(String.isNotBlank(selectedCollegeName))
        {
            List<Class__c> tempClassList = [SELECT Id, Name, College__c, College__r.Name FROM Class__c WHERE (College__r.Name != null AND College__r.Name =: selectedCollegeName) ORDER BY Name ASC];

            if(tempClassList != null && tempClassList.size() > 0)
            {
                showDepartments = true;
                for(Class__c cls : tempClassList)
                {
                    List<SelectOption> options = new List<SelectOption>();
                    if(departmentList.isEmpty()){
                        departmentList.add(new SelectOption('', '--None--'));
                    }
                    if (cls != null && cls.Name != null){
                        departmentList.add(new SelectOption(cls.Name, cls.Name));
                    }
                }
            }
        }
    }
}