force-app/main/default/objects/Class__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.College__c</field>
            <operation>equals</operation>
            <valueField>Class__c.College__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CheckRecord.cls
public class CheckRecord{
    public List<Student__c> studentList;
    
    public void getStudent(String collegeName, String departmentName, String studentName){
        studentList = [SELECT College__r.Name, Class__r.Name, Name FROM Student__c WHERE (College__r.Name = :collegeName AND Class__r.Name = :departmentName AND Name=:studentName)];
        if(studentList.size() > 0){
        }
        else{
            College__c getCollege = [SELECT Name, id FROM College__c WHERE Name = :collegeName];
            Class__c getDepartment = [SELECT Name, id FROM Class__c WHERE Name = :departmentName];
            Student__c studentRecord = new Student__c();
            studentRecord.Name = studentName;
            studentRecord.College__c = getCollege.id;
            studentRecord.Class__c = getDepartment.id;
            insert studentRecord;
        }
    }
}

/* College4 t = new College4();
t.getStudent('Kammavar College', 'CS-1', 'TestName2');

if(t.studentList.size() > 0){
System.debug(' The Student Name is Exist ');
}else{
System.debug(' New Student Record is Created ');
} */