force-app/main/default/objects/Class__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/College__c/fields/NAAC_Grade__c.field-meta.xml
<CustomField>
    <fullName>NAAC_Grade__c</fullName>
    <label>NAAC Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A++</fullName>
            </value>
            <value>
                <fullName>A+</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B++</fullName>
            </value>
            <value>
                <fullName>B+</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/College__c/fields/Pin_code__c.field-meta.xml
<CustomField>
    <fullName>Pin_code__c</fullName>
    <label>Pin code</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/College__c/fields/Total_Students__c.field-meta.xml
<CustomField>
    <fullName>Total_Students__c</fullName>
    <label>Total Students</label>
    <summaryForeignKey>Student__c.College__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.College__c</field>
            <operation>equals</operation>
            <valueField>Class__c.College__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/College.cls
public class College{
    
    public String nameOfTheCollege;
    public college__c collegeInfo(){
        List<college__c> collegeDetails = [SELECT Name, Address__c, Contact__c, CGPA__c, Website__c, E_Mail__c, NAAC_Grade__c, Pin_code__c, Total_Students__c FROM College__c WHERE Name = :nameOfTheCollege];
        if(collegeDetails.size() > 0){
            return collegeDetails.get(0);
        }else{
            System.debug(' Enter The Valid College Name ');
            return null;
        }
    }
    public List<String> getDepartmentList(){
        List<class__c> departmentDetails = [SELECT Name FROM class__c WHERE College__r.Name = :nameoftheCollege ORDER BY Name ASC];
        List<String> departmentName = new List<String>();
        for(class__c departmentList : departmentDetails){
            departmentName.add(departmentList.Name);
        }
        return departmentName;
    }
    public List<String> getStudentList(){
        List<Student__c> studentDetails = [SELECT Name, College__r.Name FROM Student__c WHERE College__r.Name = :nameOfTheCollege ORDER BY Name ASC];
        List<String> studentName = new List<String>();
        for(Student__c studentList : studentDetails){
            studentName.add(studentList.Name);
        }
        return studentName;
    }
}

/* College t = new College();
t.nameOfTheCollege = 'CPA College';

College__c test1 = new College__c();
test1 = t.collegeInfo();
if(test1 != null){
    System.debug(test1);
} */





/* college t = new college();
t.nameofTheCollege = 'CPA College';
College__c collegeRecord = t.collegeInfo();
System.debug('College Name - '+collegeRecord.get('Name'));
System.debug('NAAC Grade - '+collegeRecord.get('NAAC_Grade__c'));
System.debug('CGPA - '+collegeRecord.get('CGPA__C'));
System.debug('Address - '+collegeRecord.get('Address__c'));
System.debug('Pincode - '+collegeRecord.get('Pin_code__c'));
System.debug('Contact - '+collegeRecord.get('Contact__c'));
System.debug('Email - '+collegeRecord.get('E_Mail__c'));
System.debug('Website - '+collegeRecord.get('Website__c'));
System.debug('Total Number of Students - '+collegeRecord.get('Total_Students__c'));


System.debug(t.getDepartmentList());
System.debug(t.getStudentList()); */

/*for(class__c departmentList : t.getDepartmentList()){
System.debug(departmentList.Name);
}

for(Student__c studentList : t.getStudentList()){
System.debug(studentList.Name);
} */