force-app/main/default/objects/Class__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Blood_Group__c.field-meta.xml
<CustomField>
    <fullName>Blood_Group__c</fullName>
    <label>Blood Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A+</fullName>
            </value>
            <value>
                <fullName>A-</fullName>
            </value>
            <value>
                <fullName>B+</fullName>
            </value>
            <value>
                <fullName>B-</fullName>
            </value>
            <value>
                <fullName>O+</fullName>
            </value>
            <value>
                <fullName>O-</fullName>
            </value>
            <value>
                <fullName>AB+</fullName>
            </value>
            <value>
                <fullName>AB-</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.College__c</field>
            <operation>equals</operation>
            <valueField>Class__c.College__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/D_O_B__c.field-meta.xml
<CustomField>
    <fullName>D_O_B__c</fullName>
    <label>D.O.B</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Ms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Sudent_Active_Status__c.field-meta.xml
<CustomField>
    <fullName>Sudent_Active_Status__c</fullName>
    <label>Student Active Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Suspend</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/TotalMark__c.field-meta.xml
<CustomField>
    <fullName>TotalMark__c</fullName>
    <formula>Mark_1__c  +  Mark_2__c  + Mark_3__c  +Mark_4__c  + Mark_5__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TotalMark</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AddStudentRecord.cls
public class AddStudentRecord {
    public Student__c student{get;set;}
    public List<Student__c> studentList{get;set;}
    
    public AddStudentRecord(){
        student = new Student__c();
        studentList = [SELECT Salutation__c, Name, Gender__c, Contact_Number__c, D_O_B__c, Blood_Group__c, Sudent_Active_Status__c, TotalMark__c, Class__r.Name, College__r.Name FROM Student__c ORDER BY College__r.Name, Name, Class__r.Name, Gender__c];
        System.debug('----->' + studentList);
    }
    
    public void Save(){
        insert student;
	}
}