force-app/main/default/objects/Class__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.College__c</field>
            <operation>equals</operation>
            <valueField>Class__c.College__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/College1.cls
public class College1 {
    public List<String> departmentName(String nameOfTheCollege){
        
        List<Class__c> departmentDetails = [SELECT Name, College__r.Name FROM Class__c WHERE College__r.Name = :nameOfTheCollege];
        List<String> departmentList = new List<String>();
        for(Class__c deptList : departmentDetails){
            departmentList.add(deptList.Name);
        }
        return departmentList;  
    }
    public List<String> studentName(String collegeName, String departmentName){        
        
        List<Student__c> studentDetails = [SELECT Name, Class__r.Name, College__r.Name FROM Student__c WHERE College__r.Name = :collegeName AND Class__r.Name = :departmentName];
        List<String> studentList = new List<String>();
        for(Student__c studList : studentDetails){
            studentList.add(studList.Name);
        }
        return studentList;                
    }
}