force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mark_1__c.field-meta.xml
<CustomField>
    <fullName>Mark_1__c</fullName>
    <label>Mark 1</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mark_2__c.field-meta.xml
<CustomField>
    <fullName>Mark_2__c</fullName>
    <label>Mark 2</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mark_3__c.field-meta.xml
<CustomField>
    <fullName>Mark_3__c</fullName>
    <label>Mark 3</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mark_4__c.field-meta.xml
<CustomField>
    <fullName>Mark_4__c</fullName>
    <label>Mark 4</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mark_5__c.field-meta.xml
<CustomField>
    <fullName>Mark_5__c</fullName>
    <label>Mark 5</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/TotalMark__c.field-meta.xml
<CustomField>
    <fullName>TotalMark__c</fullName>
    <formula>Mark_1__c  +  Mark_2__c  + Mark_3__c  +Mark_4__c  + Mark_5__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TotalMark</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/collegeList.cls
public class collegeList{
    public void getStudent(String collegeName){
        
        List<Student__c> studentDetails = [SELECT Name, Mark_1__c, Mark_2__c, Mark_3__c, Mark_4__c, Mark_5__c, TotalMark__c FROM Student__c WHERE TotalMark__c != 0 AND College__r.Name = :collegeName ORDER BY TotalMark__c DESC];               
        Map<String, List<String>> collegeMap = new Map<String, List<String>>();
        
        for(Student__c stList : studentDetails){            
            List<Decimal> countList = new List<Decimal>{stList.Mark_1__c, stList.Mark_2__c, stList.Mark_3__c, stList.Mark_4__c, stList.Mark_5__c};
                List<String> addStudentName = new List<String>();
            for(Decimal checkPass : countList){
                if(checkPass>=35){
                    addStudentName.add(stList.Name);
                }
            }
            if(collegeMap.ContainsKey('Pass in 5 Subjects')){
                if(addStudentName.size() == 5){
                    List<String> tempList = collegeMap.get('Pass in 5 Subjects');
                    tempList.add(stList.Name);
                    collegeMap.put('Pass in 5 Subjects', tempList);
                }                                    
            }else{
                List<String> tempList = new List<String>();
                tempList.add(stList.Name);
                collegeMap.put('Pass in 5 Subjects', tempList);
            }
            if(collegeMap.ContainsKey('Pass in 4 Subjects')){
                if(addStudentName.size() == 4){
                    List<String> tempList = collegeMap.get('Pass in 4 Subjects');
                    tempList.add(stList.Name);
                    collegeMap.put('Pass in 4 Subjects', tempList);
                }                                
            }else{
                List<String> tempList = new List<String>();
                collegeMap.put('Pass in 4 Subjects', tempList);
            }
            if(collegeMap.ContainsKey('Pass in 3 Subjects')){
                if(addStudentName.size() == 3){
                    List<String> tempList = collegeMap.get('Pass in 3 Subjects');
                    tempList.add(stList.Name);
                    collegeMap.put('Pass in 3 Subjects', tempList);
                }                                    
            }else{
                List<String> tempList = new List<String>();
                collegeMap.put('Pass in 3 Subjects', tempList);
            }
            if(collegeMap.ContainsKey('Pass in 2 Subjects')){
                if(addStudentName.size() == 2){
                    List<String> tempList = collegeMap.get('Pass in 2 Subjects');
                    tempList.add(stList.Name);
                    collegeMap.put('Pass in 2 Subjects', tempList);
                }                                    
            }else{
                List<String> tempList = new List<String>();
                collegeMap.put('Pass in 2 Subjects', tempList);
            }
            if(collegeMap.ContainsKey('Pass in 1 Subjects')){
                if(addStudentName.size() == 1){
                    List<String> tempList = collegeMap.get('Pass in 1 Subjects');
                    tempList.add(stList.Name);
                    collegeMap.put('Pass in 1 Subjects', tempList);
                }                                    
            }else{
                List<String> tempList = new List<String>();
                collegeMap.put('Pass in 1 Subjects', tempList);
            }
            if(collegeMap.ContainsKey('Fail in All Subjects')){
                if(addStudentName.size() == 0){
                    List<String> tempList = collegeMap.get('Fail in All Subjects');
                    tempList.add(stList.Name);
                    collegeMap.put('Fail in All Subjects', tempList);
                }                                    
            }else{
                List<String> tempList = new List<String>();
                collegeMap.put('Fail in All Subjects', tempList);
            }            
        }       
        for(String getKey : collegeMap.Keyset()){
            System.debug(getKey + '--------->');
            for(String getValue : collegeMap.get(getKey)){
                System.debug(getValue);
            }
        }
    } 
}