force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mark_1__c.field-meta.xml
<CustomField>
    <fullName>Mark_1__c</fullName>
    <label>Mark 1</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mark_2__c.field-meta.xml
<CustomField>
    <fullName>Mark_2__c</fullName>
    <label>Mark 2</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mark_3__c.field-meta.xml
<CustomField>
    <fullName>Mark_3__c</fullName>
    <label>Mark 3</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mark_4__c.field-meta.xml
<CustomField>
    <fullName>Mark_4__c</fullName>
    <label>Mark 4</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mark_5__c.field-meta.xml
<CustomField>
    <fullName>Mark_5__c</fullName>
    <label>Mark 5</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/TotalMark__c.field-meta.xml
<CustomField>
    <fullName>TotalMark__c</fullName>
    <formula>Mark_1__c  +  Mark_2__c  + Mark_3__c  +Mark_4__c  + Mark_5__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TotalMark</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SortByPassMark.cls
public class SortByPassMark{
    public void getStudent(String collegeName){
        
        List<Student__c> studentDetails = [SELECT Name, Mark_1__c, Mark_2__c, Mark_3__c, Mark_4__c, Mark_5__c, TotalMark__c FROM Student__c WHERE TotalMark__c != 0 AND College__r.Name = :collegeName ORDER BY TotalMark__c DESC];               
        Map<String, List<String>> collegeMap = new Map<String, List<String>>();
        for(Student__c stList : studentDetails){
            List<Decimal> countList = new List<Decimal>{stList.Mark_1__c, stList.Mark_2__c, stList.Mark_3__c, stList.Mark_4__c, stList.Mark_5__c};
                Integer countVar = 0;             
            for(Decimal checkPass : countList){
                if(checkPass>=35){
                    countVar++;
                }
            }
            for(Integer i=5 ; i>=0; i--){
                if(collegeMap.ContainsKey('Pass in ' + i +' Subjects')){
                    if(countVar == i){          
                        List<String> tempList = collegeMap.get('Pass in ' + i +' Subjects');
                        tempList.add(stList.Name);
                    }
                }else{
                    collegeMap.put('Pass in ' + i +' Subjects', new List<String>());
                    if(countVar == 5){
                        collegeMap.put('Pass in 5 Subjects', new List<String>{stList.Name});
                    }else if(countVar == 4){
                        collegeMap.put('Pass in 4 Subjects', new List<String>{stList.Name});
                    }else if(countVar == 3){
                        collegeMap.put('Pass in 3 Subjects', new List<String>{stList.Name});
                    }else if(countVar == 2){
                        collegeMap.put('Pass in 2 Subjects', new List<String>{stList.Name});
                    }else if(countVar == 1){
                        collegeMap.put('Pass in 1 Subjects', new List<String>{stList.Name});
                    }else if(countVar == 0){
                        collegeMap.put('Pass in 0 Subjects', new List<String>{stList.Name});
                    }
                }
            }
        }
        List<String> insertNewKey = collegeMap.get('Pass in 0 Subjects');
        collegeMap.put('Fail in All Subjects', insertNewKey);
        List<String> removeKey = collegeMap.remove('Pass in 0 Subjects');
        for(String getKey : collegeMap.Keyset()){
            if(!collegeMap.get(getKey).isEmpty()){
                System.debug(getKey+'--------->');
            }
            for(String getValue : collegeMap.get(getKey)){
                System.debug(getValue);
            }
        } 
    }
}