force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mark_1__c.field-meta.xml
<CustomField>
    <fullName>Mark_1__c</fullName>
    <label>Mark 1</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mark_2__c.field-meta.xml
<CustomField>
    <fullName>Mark_2__c</fullName>
    <label>Mark 2</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mark_3__c.field-meta.xml
<CustomField>
    <fullName>Mark_3__c</fullName>
    <label>Mark 3</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mark_4__c.field-meta.xml
<CustomField>
    <fullName>Mark_4__c</fullName>
    <label>Mark 4</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Mark_5__c.field-meta.xml
<CustomField>
    <fullName>Mark_5__c</fullName>
    <label>Mark 5</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/TotalMark__c.field-meta.xml
<CustomField>
    <fullName>TotalMark__c</fullName>
    <formula>Mark_1__c  +  Mark_2__c  + Mark_3__c  +Mark_4__c  + Mark_5__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TotalMark</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdateEmail.cls
public class UpdateEmail {
    /*public static void emailmethod(){
        List <Student__c> templist = [SELECT Name, Register_Number__c, E_Mail__c FROM  Student__c];
        
        If(templist != null && templist.size() > 0){
            System.debug('Record is Found');
        }Else{
            System.debug('No Records Found');
        }
        For(Student__c tempStudent : templist){
            tempstudent.E_Mail__c = tempstudent.Name + tempstudent.Register_Number__c + '@gmail.com';
        }update templist;
    }*/

		/*Public Static void tempmethod(){
        List <Student__c> templist1 = [SELECT Name, TotalMark__c FROM Student__c ORDER BY TotalMark__c DESC];
        List<String> mylist = new list<String>();
        For(Student__c tempstudent1 : templist1){
            String st = tempstudent1.Name;
            mylist.add('\n'+st);
           
        }
        System.debug(mylist);
    }*/ 
    public static void tempmethod2(){
        List<Student__c> templist1 = [SELECT Name, Mark_1__c, Mark_2__c, Mark_3__c, Mark_4__c, Mark_5__c, TotalMark__c FROM Student__c WHERE College__r.Name = 'CPA College'];      
		List<Integer> mark1 = new List<Integer>();
        
               For(Student__c tempvar : templist1){
                 Integer m1 = Integer.valueOf(tempvar.Mark_1__c);
                 Integer m2 = Integer.valueOf(tempvar.Mark_2__c);
                 Integer m3 = Integer.valueOf(tempvar.Mark_3__c);
                 Integer m4 = Integer.valueof(tempvar.Mark_4__c);
                 Integer m5 = Integer.valueOf(tempvar.Mark_5__c);
                  
                       System.debug(tempvar.Name);
                                       
                   
  }
 }
}