force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/TotalMark__c.field-meta.xml
<CustomField>
    <fullName>TotalMark__c</fullName>
    <formula>Mark_1__c  +  Mark_2__c  + Mark_3__c  +Mark_4__c  + Mark_5__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TotalMark</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/College5.cls
public class College5 {
    public List<Student__c> studentList(String collegeName, Integer topStudents){
        List<Student__c> studentRecords = [SELECT Name, TotalMark__c FROM Student__c WHERE College__r.Name = :collegeName ORDER BY TotalMark__c DESC];
        List<Student__c> top3students = new List<Student__c>();
        List<Decimal> addTotalMark = new List<Decimal>();
        List<Decimal> finalList = new List<Decimal>();
        List<Decimal> limitList = new List<Decimal>();
        for(Student__c addRec : studentRecords){
            addTotalMark.add(addRec.TotalMark__c);
            addTotalMark.sort();
        }
        for(Integer i=addTotalMark.size()-1; i>=0; i++){
            finalList.add(addTotalMark.get(i));
        }
        for(Integer i=0; i<=topStudents; i++){
            limitList.add(finalList.get(i));
        }
        for(Student__c str : studentRecords){
            for(Decimal dt : limitList){
                if(str.TotalMark__c == dt){
                    top3students.add(str);
                }
            }
        }
        return top3Students;
    }
}