force-app/main/default/objects/College__c/College__c.object-meta.xml
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <label>College</label>
    <referenceTo>College__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/StudentsDataViewCTRL.cls
public with sharing class StudentsDataViewCTRL
{
    public List<StudentWrapper> studentList {get;set;}

    public StudentsDataViewCTRL()
    {
        studentList = new List<StudentWrapper>();
    }

    public class StudentWrapper
    {
        Contact con;
        Student__c std;
        College__c clg;
        Department__c dept;
        String studentName;
        String deptName;
        String clgName;
        String dob;
        String age;
        String sslcMarks;
        String hscMarks;
        String address;
        String email;
        String phone;

        StudentWrapper(Contact c)
        {

        }
    }

    public SObject getStudentRelatedRecords(SObject sobj)
    {
        String sObjName = sobj.Id.getSobjectType().getDescribe().getName();

        switch on (sObjName)
        {
            when 'Contact'
            {

            }
            when 'Student__c'
            {

            }
            when 'College__c'
            {

            }
            when 'Department__c'
            {

            }
        }

        return null;
    }
}