force-app/main/default/objects/Discussion__c/Discussion__c.object-meta.xml
<CustomObject>
    <label>Discussion</label>
    <nameField>
        <displayFormat>DCN-{0000}</displayFormat>
        <label>Discussion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discussions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discussion__c/fields/Account_SFDC_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_SFDC_ID__c</fullName>
    <formula>Contact__r.AccountId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account SFDC ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discussion__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Discussions</relationshipLabel>
    <relationshipName>Discussions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discussion__c/fields/Discussed_Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Discussed_Person_Name__c</fullName>
    <formula>Contact__r.FirstName  + &apos; &apos; +  Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discussed Person Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discussion__c/fields/Discussion_Title__c.field-meta.xml
<CustomField>
    <fullName>Discussion_Title__c</fullName>
    <label>Discussion Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Discussion__c/fields/Discussion_Type__c.field-meta.xml
<CustomField>
    <fullName>Discussion_Type__c</fullName>
    <label>Discussion Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DiscussionsViewInTheContactRecord.cls
public without sharing class DiscussionsViewInTheContactRecord {
    public List<Discussion__c> lstOfDiscussion {get;set;}
    public Discussion__c discusstion {get;set;}

    public DiscussionsViewInTheContactRecord(ApexPages.StandardController stdControllder){
        String conId = stdControllder.getId();
        if(String.isNotBlank(conId)){
            lstOfDiscussion = [SELECT Id, Name, Account_SFDC_ID__c, Contact__c, Description__c, Discussed_Person_Name__c, Discussion_Title__c, Discussion_Type__c FROM Discussion__c WHERE Contact__c =: conId];
        }

        // Integer inte = Integer.valueOf('asdf');
    }
}