force-app/main/default/objects/Customer_Detail__c/Customer_Detail__c.object-meta.xml
<CustomObject>
    <label>Customer Detail</label>
    <nameField>
        <label>Customer Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Details</relationshipLabel>
    <relationshipName>Customer_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DMLCustomerDetails.cls
public class DMLCustomerDetails {
    public void insertCustomerRec(){
        Contact con = new contact();
        con.FirstName = 'Muthu';
        con.LastName = 'Thottappan';
        insert con;
        
        Customer_Detail__c cusDetails = new Customer_Detail__c();
        cusDetails.Name = 'CustomerRecord1';
        cusDetails.Customer_ID__c = 'AB8925195588';
        cusDetails.Gender__c = 'Male';
        cusDetails.Contact__c = con.id;
        insert cusDetails;
    }
    
    public void updateCustomerRec(){
        List<Customer_Detail__c> cusList = [SELECT Name, Customer_ID__c, Gender__c, Contact__c FROM Customer_Detail__c LIMIT 1];
        String customerContactId = cusList[0].Contact__c;
        
        Contact con = new Contact();
        con.id = customerContactId;
        con.FirstName = 'Aathi';
        update con;
    }
}