force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{0000}</displayFormat>
        <label>Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/onSiteCheckInControllerTest.cls
@isTest(seeAllData=true)

public class onSiteCheckInControllerTest {

    static TestMethod void onSiteCheckInTest(){
        Event__c evt = new Event__c(Name = 'TestEventName');
        ApexPages.StandardController sc = new ApexPages.standardController(evt);
        OnSiteCheckInController onSiteController = new OnSiteCheckInController(sc);
        onSiteController.con = new Contact();
        onSiteController.reg = new Registration__c();
        onSiteController.event = new Event__c();
        onSiteController.note = new note();
        onSiteController.isRecordsAvailable = true;
        onSiteController.isContactInformation = false;
        onSiteController.checkInSuccessMessage = false;
        onSiteController.noDataFound = false;
        onSiteController.eventId = 'TestEventId';
        onSiteController.selectContactId = 'TestConId';
        onSiteController.regId = 'TestRegId';
        onSiteController.searchByNameandEmail = 'test@gmail.com';
        onSiteController.registrationRecords = new List<Registration__c>();
        onSiteController.registratDetails = new List<Registration__c>();
        onSiteController.noteList = new List<Note>();

        onSiteController.searchByContact();
        onSiteController.searchByRegistrationName();
        onSiteController.checkIn();
        onSiteController.getNoteList('TestRegId');
    }
}